interface ImportMetaEnv {
	VITE_MESHER_TOKEN: string;
	VITE_DISCORD_ROLE_ASSIGN_EP: string;

	VITE_KLAYTN_CAP_NFT_ENTER: string;
	VITE_KLAYTN_CAP_NFT_ENTER_LP: string;

	VITE_DISCORD_REDIRECT_URI: string;
	VITE_DISCORD_CLIENT_ID: string;
	VITE_DISCORD_CLIENT_SECRET: string;
}
